REDIS_CONFIG:
  host: "localhost"  # redis 链接
  port: 6379         # redis 端口
  auth: "xxxx"       # redis 连接密码
  db: 1              # redis 数据库

APP_TOKEN_CACHE_KEY: APP_TOKEN_CACHE_KEY

MYSQL_CONFIG:
  name: "localhost"
  type: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "xuhua1212"
  database: "nest_demo"
  synchronize: true
  entities: "mysql"

MONGODB_CONFIG:
  name: "fast_gateway_test"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
  username: "xxxx"                   # 数据库链接用户名
  password: "123456"                 # 数据库链接密码
  database: "fast_gateway_test"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
  
TEST_VALUE:
  name: Cookie
  test_value: Xuhua